---
apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: coturn
  labels:
    app: coturn
spec:
  type: ClusterIP
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: turn-udp
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: turn-tcp
  selector:
    app: coturn
