---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin-wddm
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: device-plugin-wddm
  template:
    metadata:
      labels:
        app: device-plugin-wddm
    spec:
      nodeSelector:
        kubernetes.io/os: 'windows'
        kubernetes.io/arch: 'amd64'
        node.kubernetes.io/windows-build: '10.0.20348'
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "gpu"
          effect: "NoExecute"
      hostNetwork: true
      containers:
        - name: device-plugin-wddm
          image: "index.docker.io/tensorworks/wddm-device-plugin:0.0.1"
          imagePullPolicy: Always

          # Configure the WDDM device plugin to allow 4 containers to mount each display device simultaneously
          env:
            - name: WDDM_DEVICE_PLUGIN_MULTITENANCY
              value: "4"
