---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ims-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ims-role-binding
subjects:
  - kind: ServiceAccount
    name: ims-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io