apiVersion: v1
kind: ServiceAccount
metadata:
  name: ims-service-account
  namespace: games

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ims-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ims-role-binding
subjects:
  - kind: ServiceAccount
    name: ims-service-account
    namespace: games
roleRef:
  kind: ClusterRole
  name: ims-cluster-role
  apiGroup: rbac.authorization.k8s.io